apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8snondefault
  annotations:
    description: >-
      Requires resources to not be applied to the default namespace
spec:
  crd:
    spec:
      names:
        kind: k8snondefault
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            labels:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8snondefault
                
        violation[{"msg": msg, "details": {}}] {
          not input.review.object.metadata.namespace
          msg := "Namespace should not be unspecified"       
        }

        violation[{"msg": msg, "details": {}}] {
          value := input.review.object.metadata.namespace
          count(value) == 0
          msg := sprintf("Namespace should not be empty: %v", [value])          
        }
                
        violation[{"msg": msg, "details": {}}] {
          value := input.review.object.metadata.namespace
          value == "default"
          msg := sprintf("Namespace should not be default: %v", [value])          
        }
