apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srorootfs
  annotations:
    description: >-
      Requires pods to use the securityContext readOnlyRootFilesystem as true.
spec:
  crd:
    spec:
      names:
        kind: k8srorootfs
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            labels:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srorootfs

        violation[{"msg": msg, "details": {}}] {
            input.review.object.spec.containers[_].securityContext.readOnlyRootFilesystem == true
            msg := "Pod must specify spec.containers[*].securityContext.readOnlyRootFilesystem to true"
        }

        violation[{"msg": msg, "details": {}}] {
            not input.review.object.spec.containers.securityContext.readOnlyRootFilesystem
            msg := "spec.securityContext.containers.readOnlyRootFilesystem not specified"
        }

